spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
              client-id: 2414664315458888
              client-secret: 486141bb7a67c013cf8b7c7f78e7580c
          google:
<<<<<<< HEAD
            client-id: 516189372327-1tmhn90ecfs3k5o4mue7nkjc2sk16maq.apps.googleusercontent.com
            client-secret: CYq_3XWPplr434RpRzP0jfiJ
||||||| 7185f90
            client-id:
            client-secret:
custom:
  oauth2:
    kakao:
       client-id:

      #      accessTokenUri: https://graph.facebook.com/oauth/acces_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth?display=popup
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#      scope: email
#  resource:
#    userInfoUri: https://graph.facebook.com/me?fields=id,name,email,link

#    accessTokenUri: https://accounts.google.com/o/oauth2/token
#    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
#    scope: email, profile
#  resource:
#    userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo
#
#kakao:
#  client:
#      clientId: 4edfd9af0ec0804a4b839c1f4aa77cfe
#      accessTokenUri: https://kauth.kakao.com/oauth/token
#      userAuthorizationUri: https://kauth.kakao.com/oauth/authorize
#  resource:
#    userInfoUri: https://kapi.kakao.com/v1/user/me
=======
            client-id:
            client-secret:
custom:
  oauth2:
    kakao:
       client-id:

    http:
     multipart:
        maxFileSize: 10MB
      #      accessTokenUri: https://graph.facebook.com/oauth/acces_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth?display=popup
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#      scope: email
#  resource:
#    userInfoUri: https://graph.facebook.com/me?fields=id,name,email,link

#    accessTokenUri: https://accounts.google.com/o/oauth2/token
#    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
#    scope: email, profile
#  resource:
#    userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo
#
#kakao:
#  client:
#      clientId: 4edfd9af0ec0804a4b839c1f4aa77cfe
#      accessTokenUri: https://kauth.kakao.com/oauth/token
#      userAuthorizationUri: https://kauth.kakao.com/oauth/authorize
#  resource:
#    userInfoUri: https://kapi.kakao.com/v1/user/me

>>>>>>> upstream/submaster
