spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/mysqlES
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.jdbc.Driver
#    jpa:
#      hibernate:
#        ddl-auto: create
#    h2:
#      console:
#        enabeled: false
  security:
    oauth2:
      client:
        registration:
          facebook:
              client-id:
              client-secret:
          google:
            client-id:
            client-secret:
custom:
  oauth2:
    kakao:
       client-id:

    http:
     multipart:
        maxFileSize: 10MB
      #      accessTokenUri: https://graph.facebook.com/oauth/acces_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth?display=popup
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#      scope: email
#  resource:
#    userInfoUri: https://graph.facebook.com/me?fields=id,name,email,link

#    accessTokenUri: https://accounts.google.com/o/oauth2/token
#    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
#    scope: email, profile
#  resource:
#    userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo
#
#kakao:
#  client:
#      clientId: 4edfd9af0ec0804a4b839c1f4aa77cfe
#      accessTokenUri: https://kauth.kakao.com/oauth/token
#      userAuthorizationUri: https://kauth.kakao.com/oauth/authorize
#  resource:
#    userInfoUri: https://kapi.kakao.com/v1/user/me

