spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 466913887271674
            client-secret: c863270e0bcd1195dc7483749dd3bcef
          google:
            client-id: 516189372327-1tmhn90ecfs3k5o4mue7nkjc2sk16maq.apps.googleusercontent.com
            client-secret: CYq_3XWPplr434RpRzP0jfiJ